[[redirects]]
from = "/ironwork"
to = "/index.html"
status = 200

[[redirects]]
from = "/electrics"
to = "/index.html"
status = 200

[[redirects]]
from = "/plumbing"
to = "/index.html"
status = 200

[[redirects]]
from = "/woodwork"
to = "/index.html"
status = 200

[[redirects]]
from = "/architecture"
to = "/index.html"
status = 200

[[redirects]]
from = "/koalax"
to = "/index.html"
status = 200

[[redirects]]
from = "/dropbox/callback"
to = "/index.html"
status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200